apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: nothernadav/train-schedule:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: train-schedule

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: train-schedule-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: train-schedule-service
            port:
              number: 80